# Welcome to Jekyll!

# Website settings
title: Alejandro Escontrela
description: Hi there. This is my blog, contact info, and project page.
keywords: Alejandro,Escontrela,GitHub,ML,DL,Python
baseurl:  /Ale # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://Alescontrela.github.io/Ale/  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Ale/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Alejandro Escontrela  # Be used at blog posts' author.
  first_name: Alejandro  # Be used at index page about me section.
  last_name: Escontrela  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: Alescontrela  # Leave blank if you don't have now
  linkedin_id: alejandro-escontrela # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username:
  medium_username: alejandroescontrela # Leave blank if you don't have now
  email: alejandroescontrela@gmail.com  # Leave blank if you don't have now
  cv:  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fa-code-fork
    - name: fa-linux
  skill_icon2:
    - name: fa-terminal
    - name: fa-bar-chart
  desc: Hi there, I'm Alejandro, a Computer Science and Aerospace Engineering student interested in machine learning and intelligent systems. I sometimes write about my interests. # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: https-alescontrela-github-io-ale

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-122372358-1

## google optimize
go:
  id: GTM-K9BDM45

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel:  # index page carousel switch
blog_carousel:   # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
